dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
#    - libboost-test-dev
#    - libboost-all-dev # it works
     - libboost-filesystem-dev

# for tech commit
script:
- pwd
- ls
- mkdir build
- cd build
- cmake ..
- cmake --build .
- cmake --build . --target tests
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulinkfly:$BINTRAY_API_KEY "https://api.bintray.com/content/linkfly/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
